'📦 envapt':
    - changed-files:
          - any-glob-to-any-file: 'packages/envapt/**'
'📚 docs':
    - changed-files:
          - any-glob-to-any-file: 'apps/guide/**'
          - any-glob-to-any-file: '**/*.md'
          - any-glob-to-any-file: '**/*.mdx'
'🧪 tests':
    - changed-files:
          - any-glob-to-any-file: '**/*.test.ts'
          - any-glob-to-any-file: '**/*.spec.ts'
          - any-glob-to-any-file: '**/__tests__/**/*'
'🤖 ci':
    - changed-files:
          - any-glob-to-any-file: '.github/**'
          - any-glob-to-any-file: turbo.json
          - any-glob-to-any-file: turbo.jsonc
          - any-glob-to-any-file: pnpm-workspace.yaml
          - any-glob-to-any-file: pnpm-lock.yaml
          - any-glob-to-any-file: 'tsconfig*.json'
          - any-glob-to-any-file: eslint.config.mjs
          - any-glob-to-any-file: vitest.config.ts
          - any-glob-to-any-file: tsdown.config.ts
