packages:
  - packages/*
  - apps/*

embedReadme: true

allowBuilds:
  esbuild: true
  msgpackr-extract: true
  sharp: false
  unrs-resolver: true
  workerd: true

catalogs:
  dev:
    '@cloudflare/workers-types': ^5.20260911.1
    '@seedcord/eslint-config': 2.2.1
    '@types/node': 26.5.1
    prettier: 3.9.6
    eslint: 10.10.0
    typescript: 6.0.3
    zod: 4.6.4
    vitest: 4.1.11

overrides:
  sharp@<0.35.4: ^0.35.4
  smol-toml@<1.7.1: ^1.7.1
