packages:
  - packages/*
  - apps/*

embedReadme: true

allowBuilds:
    esbuild: true
    msgpackr-extract: true
    sharp: false
    unrs-resolver: true
    workerd: true

catalogs:
    dev:
        '@seedcord/eslint-config': 1.4.2
        '@types/node': 25.9.3
        prettier: 3.8.4
        eslint: 9.39.2
        typescript: 6.0.3
        zod: 4.4.3

minimumReleaseAgeExclude:
  - '@cloudflare/vitest-pool-workers@0.16.19'
  - miniflare@4.20260623.0
  - wrangler@4.104.0
