name: Release metadata

description: Derives release PR title that includes the number of packages being published

outputs:
    title:
        description: Release PR title containing the package count.
        value: ${{ steps.metadata.outputs.title }}

runs:
    using: composite
    steps:
      - id: metadata
        name: Compute release metadata
        shell: bash
        run: |
            set -euo pipefail

                        OUTPUT=$(pnpm tsx scripts/release-metadata.ts)
                        TITLE=$(printf '%s\n' "$OUTPUT" | grep '^title=' | head -n1 | cut -d'=' -f2-)

                        if [ -z "$TITLE" ]; then
                            echo "release metadata script did not return a title" >&2
                            exit 1
                        fi

                        echo "title=$TITLE" >> "$GITHUB_OUTPUT"
